use `food_and_drink_shop`;

INSERT INTO `Location_District` (`location_district_name`, `location_district_status`, `location_city_id`) VALUES
-- Hà Nội (city_id = 1)
('Quận Ba Đình', 1, 1),
('Quận Hoàn Kiếm', 1, 1),
('Quận Hai Bà Trưng', 1, 1),
('Quận Đống Đa', 1, 1),
('Quận Tây Hồ', 1, 1),
('Quận Cầu Giấy', 1, 1),
('Quận Thanh Xuân', 1, 1),
('Quận Hoàng Mai', 1, 1),
('Quận Long Biên', 1, 1),
('Quận Nam Từ Liêm', 1, 1),
('Quận Bắc Từ Liêm', 1, 1),
('Quận Hà Đông', 1, 1),
('Huyện Sóc Sơn', 1, 1),
('Huyện Đông Anh', 1, 1),
('Huyện Gia Lâm', 1, 1),
('Huyện Đan Phượng', 1, 1),
('Huyện Hoài Đức', 1, 1),
('Huyện Thanh Oai', 1, 1),
('Huyện Thường Tín', 1, 1),
('Huyện Phú Xuyên', 1, 1),
('Huyện Ứng Hòa', 1, 1),
('Huyện Mỹ Đức', 1, 1),
('Huyện Chương Mỹ', 1, 1),
('Huyện Quốc Oai', 1, 1),
('Thị xã Sơn Tây', 1, 1),
('Huyện Ba Vì', 1, 1),
('Huyện Phúc Thọ', 1, 1),
('Huyện Thạch Thất', 1, 1),
('Huyện Mê Linh', 1, 1),
('Huyện Thanh Trì', 1, 1),

-- TP. Hồ Chí Minh (city_id = 2)
('Thành phố Thủ Đức', 1, 2),
('Quận 1', 1, 2),
('Quận 3', 1, 2),
('Quận 4', 1, 2),
('Quận 5', 1, 2),
('Quận 6', 1, 2),
('Quận 7', 1, 2),
('Quận 8', 1, 2),
('Quận 10', 1, 2),
('Quận 11', 1, 2),
('Quận 12', 1, 2),
('Quận Bình Thạnh', 1, 2),
('Quận Bình Tân', 1, 2),
('Quận Gò Vấp', 1, 2),
('Quận Phú Nhuận', 1, 2),
('Quận Tân Bình', 1, 2),
('Quận Tân Phú', 1, 2),
('Huyện Bình Chánh', 1, 2),
('Huyện Cần Giờ', 1, 2),
('Huyện Củ Chi', 1, 2),
('Huyện Hóc Môn', 1, 2),
('Huyện Nhà Bè', 1, 2),

-- Đà Nẵng (city_id = 3)
('Quận Hải Châu', 1, 3),
('Quận Thanh Khê', 1, 3),
('Quận Sơn Trà', 1, 3),
('Quận Ngũ Hành Sơn', 1, 3),
('Quận Liên Chiểu', 1, 3),
('Quận Cẩm Lệ', 1, 3),
('Huyện Hòa Vang', 1, 3),
('Huyện Hoàng Sa', 1, 3),

-- Hải Phòng (city_id = 4)
('Quận Hồng Bàng', 1, 4),
('Quận Lê Chân', 1, 4),
('Quận Ngô Quyền', 1, 4),
('Quận Kiến An', 1, 4),
('Quận Hải An', 1, 4),
('Quận Đồ Sơn', 1, 4),
('Quận Dương Kinh', 1, 4),
('Huyện Thủy Nguyên', 1, 4),
('Huyện An Dương', 1, 4),
('Huyện An Lão', 1, 4),
('Huyện Kiến Thụy', 1, 4),
('Huyện Tiên Lãng', 1, 4),
('Huyện Vĩnh Bảo', 1, 4),
('Huyện Cát Hải', 1, 4),
('Huyện Bạch Long Vĩ', 1, 4),

-- Cần Thơ (city_id = 5)
('Quận Ninh Kiều', 1, 5),
('Quận Ô Môn', 1, 5),
('Quận Bình Thủy', 1, 5),
('Quận Cái Răng', 1, 5),
('Quận Thốt Nốt', 1, 5),
('Huyện Vĩnh Thạnh', 1, 5),
('Huyện Cờ Đỏ', 1, 5),
('Huyện Phong Điền', 1, 5),
('Huyện Thới Lai', 1, 5),

-- An Giang (city_id = 6)
('Thành phố Long Xuyên', 1, 6),
('Thành phố Châu Đốc', 1, 6),
('Thị xã Tân Châu', 1, 6),
('Huyện An Phú', 1, 6),
('Huyện Châu Phú', 1, 6),
('Huyện Châu Thành', 1, 6),
('Huyện Chợ Mới', 1, 6),
('Huyện Phú Tân', 1, 6),
('Huyện Thoại Sơn', 1, 6),
('Huyện Tịnh Biên', 1, 6),
('Huyện Tri Tôn', 1, 6),

-- Bà Rịa - Vũng Tàu (city_id = 7)
('Thành phố Vũng Tàu', 1, 7),
('Thành phố Bà Rịa', 1, 7),
('Huyện Châu Đức', 1, 7),
('Huyện Côn Đảo', 1, 7),
('Huyện Đất Đỏ', 1, 7),
('Huyện Long Điền', 1, 7),
('Huyện Tân Thành', 1, 7),
('Huyện Xuyên Mộc', 1, 7),

-- Bắc Giang (city_id = 8)
('Thành phố Bắc Giang', 1, 8),
('Huyện Hiệp Hòa', 1, 8),
('Huyện Lạng Giang', 1, 8),
('Huyện Lục Nam', 1, 8),
('Huyện Lục Ngạn', 1, 8),
('Huyện Sơn Động', 1, 8),
('Huyện Tân Yên', 1, 8),
('Huyện Việt Yên', 1, 8),
('Huyện Yên Dũng', 1, 8),
('Huyện Yên Thế', 1, 8),

-- Bắc Kạn (city_id = 9)
('Thành phố Bắc Kạn', 1, 9),
('Huyện Ba Bể', 1, 9),
('Huyện Bạch Thông', 1, 9),
('Huyện Chợ Đồn', 1, 9),
('Huyện Chợ Mới', 1, 9),
('Huyện Na Rì', 1, 9),
('Huyện Ngân Sơn', 1, 9),
('Huyện Pác Nặm', 1, 9),

-- Bạc Liêu (city_id = 10)
('Thành phố Bạc Liêu', 1, 10),
('Thị xã Giá Rai', 1, 10),
('Huyện Đông Hải', 1, 10),
('Huyện Hòa Bình', 1, 10),
('Huyện Hồng Dân', 1, 10),
('Huyện Phước Long', 1, 10),
('Huyện Vĩnh Lợi', 1, 10),

-- Bắc Ninh (city_id = 11)
('Thành phố Bắc Ninh', 1, 11),
('Thị xã Từ Sơn', 1, 11),
('Huyện Gia Bình', 1, 11),
('Huyện Lương Tài', 1, 11),
('Huyện Quế Võ', 1, 11),
('Huyện Thuận Thành', 1, 11),
('Huyện Tiên Du', 1, 11),
('Huyện Yên Phong', 1, 11),

-- Bến Tre (city_id = 12)
('Thành phố Bến Tre', 1, 12),
('Huyện Ba Tri', 1, 12),
('Huyện Bình Đại', 1, 12),
('Huyện Châu Thành', 1, 12),
('Huyện Chợ Lách', 1, 12),
('Huyện Giồng Trôm', 1, 12),
('Huyện Mỏ Cày Bắc', 1, 12),
('Huyện Mỏ Cày Nam', 1, 12),
('Huyện Thạnh Phú', 1, 12),

-- Bình Định (city_id = 13)
('Thành phố Quy Nhơn', 1, 13),
('Thị xã An Nhơn', 1, 13),
('Thị xã Hoài Nhơn', 1, 13),
('Huyện An Lão', 1, 13),
('Huyện Hoài Ân', 1, 13),
('Huyện Phù Cát', 1, 13),
('Huyện Phù Mỹ', 1, 13),
('Huyện Tây Sơn', 1, 13),
('Huyện Tuy Phước', 1, 13),
('Huyện Vân Canh', 1, 13),
('Huyện Vĩnh Thạnh', 1, 13),

-- Bình Dương (city_id = 14)
('Thành phố Thủ Dầu Một', 1, 14),
('Thành phố Dĩ An', 1, 14),
('Thành phố Thuận An', 1, 14),
('Thị xã Bến Cát', 1, 14),
('Thị xã Tân Uyên', 1, 14),
('Huyện Bắc Tân Uyên', 1, 14),
('Huyện Bàu Bàng', 1, 14),
('Huyện Dầu Tiếng', 1, 14),
('Huyện Phú Giáo', 1, 14),

-- Bình Phước (city_id = 15)
('Thành phố Đồng Xoài', 1, 15),
('Thị xã Bình Long', 1, 15),
('Thị xã Phước Long', 1, 15),
('Huyện Bù Đăng', 1, 15),
('Huyện Bù Đốp', 1, 15),
('Huyện Bù Gia Mập', 1, 15),
('Huyện Chơn Thành', 1, 15),
('Huyện Đồng Phú', 1, 15),
('Huyện Hớn Quản', 1, 15),
('Huyện Lộc Ninh', 1, 15),
('Huyện Phú Riềng', 1, 15),

-- Bình Thuận (city_id = 16)
('Thành phố Phan Thiết', 1, 16),
('Thị xã La Gi', 1, 16),
('Huyện Bắc Bình', 1, 16),
('Huyện Đức Linh', 1, 16),
('Huyện Hàm Tân', 1, 16),
('Huyện Hàm Thuận Bắc', 1, 16),
('Huyện Hàm Thuận Nam', 1, 16),
('Huyện Phú Quí', 1, 16),
('Huyện Tánh Linh', 1, 16),
('Huyện Tuy Phong', 1, 16),

-- Cà Mau (city_id = 17)
('Thành phố Cà Mau', 1, 17),
('Huyện Cái Nước', 1, 17),
('Huyện Đầm Dơi', 1, 17),
('Huyện Năm Căn', 1, 17),
('Huyện Ngọc Hiển', 1, 17),
('Huyện Phú Tân', 1, 17),
('Huyện Thới Bình', 1, 17),
('Huyện Trần Văn Thời', 1, 17),
('Huyện U Minh', 1, 17),

-- Cao Bằng (city_id = 18)
('Thành phố Cao Bằng', 1, 18),
('Huyện Bảo Lạc', 1, 18),
('Huyện Bảo Lâm', 1, 18),
('Huyện Hạ Lang', 1, 18),
('Huyện Hà Quảng', 1, 18),
('Huyện Hòa An', 1, 18),
('Huyện Nguyên Bình', 1, 18),
('Huyện Quảng Hòa', 1, 18),
('Huyện Thạch An', 1, 18),
('Huyện Trùng Khánh', 1, 18),

-- Đắk Lắk (city_id = 19)
('Thành phố Buôn Ma Thuột', 1, 19),
('Thị xã Buôn Hồ', 1, 19),
('Huyện Buôn Đôn', 1, 19),
('Huyện Cư Kuin', 1, 19),
('Huyện Cư M`gar', 1, 19),
('Huyện Ea H`leo', 1, 19),
('Huyện Ea Kar', 1, 19),
('Huyện Ea Súp', 1, 19),
('Huyện Krông Ana', 1, 19),
('Huyện Krông Bông', 1, 19),
('Huyện Krông Buk', 1, 19),
('Huyện Krông Năng', 1, 19),
('Huyện Krông Pắc', 1, 19),
('Huyện Lắk', 1, 19),
('Huyện M`Đrắk', 1, 19),

-- Đắk Nông (city_id = 20)
('Thành phố Gia Nghĩa', 1, 20),
('Huyện Cư Jút', 1, 20),
('Huyện Đắk Glong', 1, 20),
('Huyện Đắk Mil', 1, 20),
('Huyện Đắk R`Lấp', 1, 20),
('Huyện Đắk Song', 1, 20),
('Huyện Krông Nô', 1, 20),
('Huyện Tuy Đức', 1, 20),

-- Điện Biên (city_id = 21)
('Thành phố Điện Biên Phủ', 1, 21),
('Thị xã Mường Lay', 1, 21),
('Huyện Điện Biên', 1, 21),
('Huyện Điện Biên Đông', 1, 21),
('Huyện Mường Ảng', 1, 21),
('Huyện Mường Chà', 1, 21),
('Huyện Mường Nhé', 1, 21),
('Huyện Mường Nhùn', 1, 21),
('Huyện Nậm Pồ', 1, 21),
('Huyện Tủa Chùa', 1, 21),

-- Đồng Nai (city_id = 22)
('Thành phố Biên Hòa', 1, 22),
('Thành phố Long Khánh', 1, 22),
('Huyện Cẩm Mỹ', 1, 22),
('Huyện Định Quán', 1, 22),
('Huyện Long Thành', 1, 22),
('Huyện Nhơn Trạch', 1, 22),
('Huyện Tân Phú', 1, 22),
('Huyện Thống Nhất', 1, 22),
('Huyện Trảng Bom', 1, 22),
('Huyện Vĩnh Cửu', 1, 22),
('Huyện Xuân Lộc', 1, 22),

-- Đồng Tháp (city_id = 23)
('Thành phố Cao Lãnh', 1, 23),
('Thành phố Sa Đéc', 1, 23),
('Thành phố Hồng Ngự', 1, 23),
('Huyện Cao Lãnh', 1, 23),
('Huyện Châu Thành', 1, 23),
('Huyện Hồng Ngự', 1, 23),
('Huyện Lai Vung', 1, 23),
('Huyện Lấp Vò', 1, 23),
('Huyện Thanh Bình', 1, 23),
('Huyện Tam Nông', 1, 23),
('Huyện Tân Hồng', 1, 23),
('Huyện Tháp Mười', 1, 23),

-- Gia Lai (city_id = 24)
('Thành phố Pleiku', 1, 24),
('Thị xã An Khê', 1, 24),
('Thị xã Ayun Pa', 1, 24),
('Huyện Chư Păh', 1, 24),
('Huyện Chư Prông', 1, 24),
('Huyện Chư Pưh', 1, 24),
('Huyện Chư Sê', 1, 24),
('Huyện Đăk Đoa', 1, 24),
('Huyện Đăk Pơ', 1, 24),
('Huyện Đức Cơ', 1, 24),
('Huyện Ia Grai', 1, 24),
('Huyện Ia Pa', 1, 24),
('Huyện Kbang', 1, 24),
('Huyện Kông Chro', 1, 24),
('Huyện Krông Pa', 1, 24),
('Huyện Mang Yang', 1, 24),
('Huyện Phú Thiện', 1, 24),

-- Hà Giang (city_id = 25)
('Thành phố Hà Giang', 1, 25),
('Huyện Bắc Mê', 1, 25),
('Huyện Bắc Quang', 1, 25),
('Huyện Đồng Văn', 1, 25),
('Huyện Hoàng Su Phì', 1, 25),
('Huyện Mèo Vạc', 1, 25),
('Huyện Quản Bạ', 1, 25),
('Huyện Quang Bình', 1, 25),
('Huyện Vị Xuyên', 1, 25),
('Huyện Xín Mần', 1, 25),
('Huyện Yên Minh', 1, 25),

-- Hà Nam (city_id = 26)
('Thành phố Phủ Lý', 1, 26),
('Thị xã Duy Tiên', 1, 26),
('Huyện Bình Lục', 1, 26),
('Huyện Kim Bảng', 1, 26),
('Huyện Lý Nhân', 1, 26),
('Huyện Thanh Liêm', 1, 26),

-- Hà Tĩnh (city_id = 27)
('Thành phố Hà Tĩnh', 1, 27),
('Thị xã Hồng Lĩnh', 1, 27),
('Thị xã Kỳ Anh', 1, 27),
('Huyện Cẩm Xuyên', 1, 27),
('Huyện Can Lộc', 1, 27),
('Huyện Đức Thọ', 1, 27),
('Huyện Hương Khê', 1, 27),
('Huyện Hương Sơn', 1, 27),
('Huyện Kỳ Anh', 1, 27),
('Huyện Lộc Hà', 1, 27),
('Huyện Nghi Xuân', 1, 27),
('Huyện Thạch Hà', 1, 27),
('Huyện Vũ Quang', 1, 27),

-- Hải Dương (city_id = 28)
('Thành phố Hải Dương', 1, 28),
('Thành phố Chí Linh', 1, 28),
('Huyện Bình Giang', 1, 28),
('Huyện Cẩm Giàng', 1, 28),
('Huyện Gia Lộc', 1, 28),
('Huyện Kim Thành', 1, 28),
('Huyện Nam Sách', 1, 28),
('Huyện Ninh Giang', 1, 28),
('Huyện Thanh Hà', 1, 28),
('Huyện Thanh Miện', 1, 28),
('Huyện Tứ Kỳ', 1, 28),
('Huyện Kinh Môn', 1, 28),

-- Hậu Giang (city_id = 29)
('Thành phố Vị Thanh', 1, 29),
('Thành phố Ngã Bảy', 1, 29),
('Thị xã Long Mỹ', 1, 29),
('Huyện Châu Thành', 1, 29),
('Huyện Châu Thành A', 1, 29),
('Huyện Long Mỹ', 1, 29),
('Huyện Phụng Hiệp', 1, 29),
('Huyện Vị Thủy', 1, 29),

-- Hòa Bình (city_id = 30)
('Thành phố Hòa Bình', 1, 30),
('Huyện Cao Phong', 1, 30),
('Huyện Đà Bắc', 1, 30),
('Huyện Kim Bôi', 1, 30),
('Huyện Kỳ Sơn', 1, 30),
('Huyện Lạc Sơn', 1, 30),
('Huyện Lạc Thủy', 1, 30),
('Huyện Lương Sơn', 1, 30),
('Huyện Mai Châu', 1, 30),
('Huyện Tân Lạc', 1, 30),
('Huyện Yên Thủy', 1, 30),

-- Hưng Yên (city_id = 31)
('Thành phố Hưng Yên', 1, 31),
('Thị xã Mỹ Hào', 1, 31),
('Huyện Ân Thi', 1, 31),
('Huyện Khoái Châu', 1, 31),
('Huyện Kim Động', 1, 31),
('Huyện Phù Cừ', 1, 31),
('Huyện Tiên Lữ', 1, 31),
('Huyện Văn Giang', 1, 31),
('Huyện Văn Lâm', 1, 31),
('Huyện Yên Mỹ', 1, 31),

-- Khánh Hòa (city_id = 32)
('Thành phố Nha Trang', 1, 32),
('Thành phố Cam Ranh', 1, 32),
('Thị xã Ninh Hòa', 1, 32),
('Huyện Cam Lâm', 1, 32),
('Huyện Diên Khánh', 1, 32),
('Huyện Khánh Sơn', 1, 32),
('Huyện Khánh Vĩnh', 1, 32),
('Huyện Trường Sa', 1, 32),
('Huyện Vạn Ninh', 1, 32),

-- Kiên Giang (city_id = 33)
('Thành phố Rạch Giá', 1, 33),
('Thành phố Hà Tiên', 1, 33),
('Huyện An Biên', 1, 33),
('Huyện An Minh', 1, 33),
('Huyện Châu Thành', 1, 33),
('Huyện Giang Thành', 1, 33),
('Huyện Giồng Riềng', 1, 33),
('Huyện Gò Quao', 1, 33),
('Huyện Hòn Đất', 1, 33),
('Huyện Kiên Hải', 1, 33),
('Huyện Kiên Lương', 1, 33),
('Huyện Phú Quốc', 1, 33),
('Huyện Tân Hiệp', 1, 33),
('Huyện U Minh Thượng', 1, 33),
('Huyện Vĩnh Thuận', 1, 33),

-- Kon Tum (city_id = 34)
('Thành phố Kon Tum', 1, 34),
('Huyện Đăk Glei', 1, 34),
('Huyện Đăk Hà', 1, 34),
('Huyện Đăk Tô', 1, 34),
('Huyện Ia H`Drai', 1, 34),
('Huyện Kon Plông', 1, 34),
('Huyện Kon Rẫy', 1, 34),
('Huyện Ngọc Hồi', 1, 34),
('Huyện Sa Thầy', 1, 34),
('Huyện Tu Mơ Rông', 1, 34),

-- Lai Châu (city_id = 35)
('Thành phố Lai Châu', 1, 35),
('Huyện Mường Tè', 1, 35),
('Huyện Nậm Nhùn', 1, 35),
('Huyện Phong Thổ', 1, 35),
('Huyện Sìn Hồ', 1, 35),
('Huyện Tam Đường', 1, 35),
('Huyện Tân Uyên', 1, 35),
('Huyện Than Uyên', 1, 35),

-- Lâm Đồng (city_id = 36)
('Thành phố Đà Lạt', 1, 36),
('Thành phố Bảo Lộc', 1, 36),
('Huyện Bảo Lâm', 1, 36),
('Huyện Cát Tiên', 1, 36),
('Huyện Đạ Huoai', 1, 36),
('Huyện Đạ Tẻh', 1, 36),
('Huyện Đam Rông', 1, 36),
('Huyện Di Linh', 1, 36),
('Huyện Đơn Dương', 1, 36),
('Huyện Đức Trọng', 1, 36),
('Huyện Lạc Dương', 1, 36),
('Huyện Lâm Hà', 1, 36),

-- Lạng Sơn (city_id = 37)
('Thành phố Lạng Sơn', 1, 37),
('Huyện Bắc Sơn', 1, 37),
('Huyện Bình Gia', 1, 37),
('Huyện Cao Lộc', 1, 37),
('Huyện Chi Lăng', 1, 37),
('Huyện Đình Lập', 1, 37),
('Huyện Hữu Lũng', 1, 37),
('Huyện Lộc Bình', 1, 37),
('Huyện Tràng Định', 1, 37),
('Huyện Văn Lãng', 1, 37),
('Huyện Văn Quan', 1, 37),

-- Lào Cai (city_id = 38)
('Thành phố Lào Cai', 1, 38),
('Thị xã Sa Pa', 1, 38),
('Huyện Bảo Thắng', 1, 38),
('Huyện Bảo Yên', 1, 38),
('Huyện Bát Xát', 1, 38),
('Huyện Bắc Hà', 1, 38),
('Huyện Mường Khương', 1, 38),
('Huyện Si Ma Cai', 1, 38),
('Huyện Văn Bàn', 1, 38),

-- Long An (city_id = 39)
('Thành phố Tân An', 1, 39),
('Thị xã Kiến Tường', 1, 39),
('Huyện Bến Lức', 1, 39),
('Huyện Cần Đước', 1, 39),
('Huyện Cần Giuộc', 1, 39),
('Huyện Châu Thành', 1, 39),
('Huyện Đức Hòa', 1, 39),
('Huyện Đức Huệ', 1, 39),
('Huyện Mộc Hóa', 1, 39),
('Huyện Tân Hưng', 1, 39),
('Huyện Tân Thạnh', 1, 39),
('Huyện Tân Trụ', 1, 39),
('Huyện Thạnh Hóa', 1, 39),
('Huyện Thủ Thừa', 1, 39),
('Huyện Vĩnh Hưng', 1, 39),

-- Nam Định (city_id = 40)
('Thành phố Nam Định', 1, 40),
('Huyện Giao Thủy', 1, 40),
('Huyện Hải Hậu', 1, 40),
('Huyện Mỹ Lộc', 1, 40),
('Huyện Nam Trực', 1, 40),
('Huyện Nghĩa Hưng', 1, 40),
('Huyện Trực Ninh', 1, 40),
('Huyện Vụ Bản', 1, 40),
('Huyện Xuân Trường', 1, 40),
('Huyện Ý Yên', 1, 40),

-- Nghệ An (city_id = 41)
('Thành phố Vinh', 1, 41),
('Thị xã Cửa Lò', 1, 41),
('Thị xã Hoàng Mai', 1, 41),
('Thị xã Thái Hòa', 1, 41),
('Huyện Anh Sơn', 1, 41),
('Huyện Con Cuông', 1, 41),
('Huyện Diễn Châu', 1, 41),
('Huyện Đô Lương', 1, 41),
('Huyện Hưng Nguyên', 1, 41),
('Huyện Kỳ Sơn', 1, 41),
('Huyện Nam Đàn', 1, 41),
('Huyện Nghi Lộc', 1, 41),
('Huyện Nghĩa Đàn', 1, 41),
('Huyện Quế Phong', 1, 41),
('Huyện Quỳ Châu', 1, 41),
('Huyện Quỳ Hợp', 1, 41),
('Huyện Quỳnh Lưu', 1, 41),
('Huyện Tân Kỳ', 1, 41),
('Huyện Thanh Chương', 1, 41),
('Huyện Tương Dương', 1, 41),
('Huyện Yên Thành', 1, 41),

-- Ninh Bình (city_id = 42)
('Thành phố Ninh Bình', 1, 42),
('Thành phố Tam Điệp', 1, 42),
('Huyện Gia Viễn', 1, 42),
('Huyện Hoa Lư', 1, 42),
('Huyện Kim Sơn', 1, 42),
('Huyện Nho Quan', 1, 42),
('Huyện Yên Khánh', 1, 42),
('Huyện Yên Mô', 1, 42),

-- Ninh Thuận (city_id = 43)
('Thành phố Phan Rang-Tháp Chàm', 1, 43),
('Huyện Bác Ái', 1, 43),
('Huyện Ninh Hải', 1, 43),
('Huyện Ninh Phước', 1, 43),
('Huyện Ninh Sơn', 1, 43),
('Huyện Thuận Bắc', 1, 43),
('Huyện Thuận Nam', 1, 43),

-- Phú Thọ (city_id = 44)
('Thành phố Việt Trì', 1, 44),
('Thị xã Phú Thọ', 1, 44),
('Huyện Cẩm Khê', 1, 44),
('Huyện Đoan Hùng', 1, 44),
('Huyện Hạ Hòa', 1, 44),
('Huyện Lâm Thao', 1, 44),
('Huyện Phù Ninh', 1, 44),
('Huyện Tam Nông', 1, 44),
('Huyện Tân Sơn', 1, 44),
('Huyện Thanh Ba', 1, 44),
('Huyện Thanh Sơn', 1, 44),
('Huyện Thanh Thủy', 1, 44),
('Huyện Yên Lập', 1, 44),

-- Phú Yên (city_id = 45)
('Thành phố Tuy Hòa', 1, 45),
('Thị xã Sông Cầu', 1, 45),
('Thị xã Đông Hòa', 1, 45),
('Huyện Đồng Xuân', 1, 45),
('Huyện Phú Hòa', 1, 45),
('Huyện Sơn Hòa', 1, 45),
('Huyện Sông Hinh', 1, 45),
('Huyện Tây Hòa', 1, 45),
('Huyện Tuy An', 1, 45),

-- Quảng Bình (city_id = 46)
('Thành phố Đồng Hới', 1, 46),
('Huyện Bố Trạch', 1, 46),
('Huyện Lệ Thủy', 1, 46),
('Huyện Minh Hóa', 1, 46),
('Huyện Quảng Ninh', 1, 46),
('Huyện Quảng Trạch', 1, 46),
('Huyện Tuyên Hóa', 1, 46),
('Thị xã Ba Đồn', 1, 46),

-- Quảng Nam (city_id = 47)
('Thành phố Tam Kỳ', 1, 47),
('Thành phố Hội An', 1, 47),
('Huyện Bắc Trà My', 1, 47),
('Huyện Duy Xuyên', 1, 47),
('Huyện Đại Lộc', 1, 47),
('Huyện Đông Giang', 1, 47),
('Huyện Hiệp Đức', 1, 47),
('Huyện Nam Giang', 1, 47),
('Huyện Nam Trà My', 1, 47),
('Huyện Nông Sơn', 1, 47),
('Huyện Núi Thành', 1, 47),
('Huyện Phú Ninh', 1, 47),
('Huyện Phước Sơn', 1, 47),
('Huyện Quế Sơn', 1, 47),
('Huyện Tây Giang', 1, 47),
('Huyện Thăng Bình', 1, 47),
('Huyện Tiên Phước', 1, 47),
('Thị xã Điện Bàn', 1, 47),

-- Quảng Ngãi (city_id = 48)
('Thành phố Quảng Ngãi', 1, 48),
('Huyện Ba Tơ', 1, 48),
('Huyện Bình Sơn', 1, 48),
('Huyện Đức Phổ', 1, 48),
('Huyện Lý Sơn', 1, 48),
('Huyện Minh Long', 1, 48),
('Huyện Mộ Đức', 1, 48),
('Huyện Nghĩa Hành', 1, 48),
('Huyện Sơn Hà', 1, 48),
('Huyện Sơn Tây', 1, 48),
('Huyện Sơn Tịnh', 1, 48),
('Huyện Tư Nghĩa', 1, 48),
('Huyện Trà Bồng', 1, 48),
('Huyện Tây Trà', 1, 48),

-- Quảng Ninh (city_id = 49)
('Thành phố Hạ Long', 1, 49),
('Thành phố Cẩm Phả', 1, 49),
('Thành phố Móng Cái', 1, 49),
('Thành phố Uông Bí', 1, 49),
('Thị xã Đông Triều', 1, 49),
('Thị xã Quảng Yên', 1, 49),
('Huyện Ba Chẽ', 1, 49),
('Huyện Bình Liêu', 1, 49),
('Huyện Cô Tô', 1, 49),
('Huyện Đầm Hà', 1, 49),
('Huyện Hải Hà', 1, 49),
('Huyện Tiên Yên', 1, 49),
('Huyện Vân Đồn', 1, 49),

-- Quảng Trị (city_id = 50)
('Thành phố Đông Hà', 1, 50),
('Thị xã Quảng Trị', 1, 50),
('Huyện Cam Lộ', 1, 50),
('Huyện Cồn Cỏ', 1, 50),
('Huyện Đa Krông', 1, 50),
('Huyện Gio Linh', 1, 50),
('Huyện Hải Lăng', 1, 50),
('Huyện Hướng Hóa', 1, 50),
('Huyện Triệu Phong', 1, 50),
('Huyện Vĩnh Linh', 1, 50),

-- Sóc Trăng (city_id = 51)
('Thành phố Sóc Trăng', 1, 51),
('Thị xã Ngã Năm', 1, 51),
('Thị xã Vĩnh Châu', 1, 51),
('Huyện Cù Lao Dung', 1, 51),
('Huyện Châu Thành', 1, 51),
('Huyện Kế Sách', 1, 51),
('Huyện Long Phú', 1, 51),
('Huyện Mỹ Tú', 1, 51),
('Huyện Mỹ Xuyên', 1, 51),
('Huyện Thạnh Trị', 1, 51),
('Huyện Trần Đề', 1, 51),

-- Sơn La (city_id = 52)
('Thành phố Sơn La', 1, 52),
('Huyện Bắc Yên', 1, 52),
('Huyện Mai Sơn', 1, 52),
('Huyện Mộc Châu', 1, 52),
('Huyện Mường La', 1, 52),
('Huyện Phù Yên', 1, 52),
('Huyện Quỳnh Nhai', 1, 52),
('Huyện Sông Mã', 1, 52),
('Huyện Sốp Cộp', 1, 52),
('Huyện Thuận Châu', 1, 52),
('Huyện Vân Hồ', 1, 52),
('Huyện Yên Châu', 1, 52),

-- Tây Ninh (city_id = 53)
('Thành phố Tây Ninh', 1, 53),
('Huyện Bến Cầu', 1, 53),
('Huyện Châu Thành', 1, 53),
('Huyện Dương Minh Châu', 1, 53),
('Huyện Gò Dầu', 1, 53),
('Huyện Hòa Thành', 1, 53),
('Huyện Tân Biên', 1, 53),
('Huyện Tân Châu', 1, 53),
('Huyện Trảng Bàng', 1, 53),

-- Thái Bình (city_id = 54)
('Thành phố Thái Bình', 1, 54),
('Huyện Đông Hưng', 1, 54),
('Huyện Hưng Hà', 1, 54),
('Huyện Kiến Xương', 1, 54),
('Huyện Quỳnh Phụ', 1, 54),
('Huyện Thái Thụy', 1, 54),
('Huyện Tiền Hải', 1, 54),
('Huyện Vũ Thư', 1, 54),

-- Thái Nguyên (city_id = 55)
('Thành phố Thái Nguyên', 1, 55),
('Thành phố Sông Công', 1, 55),
('Thị xã Phổ Yên', 1, 55),
('Huyện Đại Từ', 1, 55),
('Huyện Định Hóa', 1, 55),
('Huyện Đồng Hỷ', 1, 55),
('Huyện Phú Bình', 1, 55),
('Huyện Phú Lương', 1, 55),
('Huyện Võ Nhai', 1, 55),

-- Thanh Hóa (city_id = 56)
('Thành phố Thanh Hóa', 1, 56),
('Thị xã Bỉm Sơn', 1, 56),
('Thị xã Nghi Sơn', 1, 56),
('Huyện Bá Thước', 1, 56),
('Huyện Cẩm Thủy', 1, 56),
('Huyện Đông Sơn', 1, 56),
('Huyện Hà Trung', 1, 56),
('Huyện Hậu Lộc', 1, 56),
('Huyện Hoằng Hóa', 1, 56),
('Huyện Lang Chánh', 1, 56),
('Huyện Mường Lát', 1, 56),
('Huyện Nga Sơn', 1, 56),
('Huyện Ngọc Lặc', 1, 56),
('Huyện Như Thanh', 1, 56),
('Huyện Như Xuân', 1, 56),
('Huyện Nông Cống', 1, 56),
('Huyện Quan Hóa', 1, 56),
('Huyện Quan Sơn', 1, 56),
('Huyện Quảng Xương', 1, 56),
('Huyện Thạch Thành', 1, 56),
('Huyện Thiệu Hóa', 1, 56),
('Huyện Thọ Xuân', 1, 56),
('Huyện Thường Xuân', 1, 56),
('Huyện Tĩnh Gia', 1, 56),
('Huyện Triệu Sơn', 1, 56),
('Huyện Vĩnh Lộc', 1, 56),
('Huyện Yên Định', 1, 56),

-- Thừa Thiên Huế (city_id = 57)
('Thành phố Huế', 1, 57),
('Huyện A Lưới', 1, 57),
('Huyện Nam Đông', 1, 57),
('Huyện Phong Điền', 1, 57),
('Huyện Phú Lộc', 1, 57),
('Huyện Phú Vang', 1, 57),
('Huyện Quảng Điền', 1, 57),
('Thị xã Hương Thủy', 1, 57),
('Thị xã Hương Trà', 1, 57),

-- Tiền Giang (city_id = 58)
('Thành phố Mỹ Tho', 1, 58),
('Thị xã Cai Lậy', 1, 58),
('Thị xã Gò Công', 1, 58),
('Huyện Cái Bè', 1, 58),
('Huyện Cai Lậy', 1, 58),
('Huyện Châu Thành', 1, 58),
('Huyện Chợ Gạo', 1, 58),
('Huyện Gò Công Đông', 1, 58),
('Huyện Gò Công Tây', 1, 58),
('Huyện Tân Phú Đông', 1, 58),
('Huyện Tân Phước', 1, 58),

-- Trà Vinh (city_id = 59)
('Thành phố Trà Vinh', 1, 59),
('Huyện Càng Long', 1, 59),
('Huyện Cầu Kè', 1, 59),
('Huyện Cầu Ngang', 1, 59),
('Huyện Châu Thành', 1, 59),
('Huyện Duyên Hải', 1, 59),
('Huyện Tiểu Cần', 1, 59),
('Huyện Trà Cú', 1, 59),
('Thị xã Duyên Hải', 1, 59),

-- Tuyên Quang (city_id = 60)
('Thành phố Tuyên Quang', 1, 60),
('Huyện Chiêm Hóa', 1, 60),
('Huyện Hàm Yên', 1, 60),
('Huyện Lâm Bình', 1, 60),
('Huyện Na Hang', 1, 60),
('Huyện Sơn Dương', 1, 60),
('Huyện Yên Sơn', 1, 60),

-- Vĩnh Long (city_id = 61)
('Thành phố Vĩnh Long', 1, 61),
('Thị xã Bình Minh', 1, 61),
('Huyện Bình Tân', 1, 61),
('Huyện Long Hồ', 1, 61),
('Huyện Mang Thít', 1, 61),
('Huyện Tam Bình', 1, 61),
('Huyện Trà Ôn', 1, 61),
('Huyện Vũng Liêm', 1, 61),

-- Vĩnh Phúc (city_id = 62)
('Thành phố Vĩnh Yên', 1, 62),
('Thành phố Phúc Yên', 1, 62),
('Huyện Bình Xuyên', 1, 62),
('Huyện Lập Thạch', 1, 62),
('Huyện Sông Lô', 1, 62),
('Huyện Tam Dương', 1, 62),
('Huyện Tam Đảo', 1, 62),
('Huyện Vĩnh Tường', 1, 62),
('Huyện Yên Lạc', 1, 62),

-- Yên Bái (city_id = 63)
('Thành phố Yên Bái', 1, 63),
('Thị xã Nghĩa Lộ', 1, 63),
('Huyện Lục Yên', 1, 63),
('Huyện Mù Cang Chải', 1, 63),
('Huyện Trạm Tấu', 1, 63),
('Huyện Trấn Yên', 1, 63),
('Huyện Văn Chấn', 1, 63),
('Huyện Văn Yên', 1, 63),
('Huyện Yên Bình', 1, 63);

SELECT * FROM `Location_District`;