import type { Metadata } from "next";
import AppModalProvider from "@/contexts/modal/AppModalProvider";
import MessageModalProviderRoot from "@/contexts/message/MessageModalProviderRoot";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { AccountProvider } from "../contexts/AccountContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App - localhost",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AccountProvider>
          <MessageModalProviderRoot>
            <AppModalProvider>
              {children}
            </AppModalProvider>
          </MessageModalProviderRoot>
        </AccountProvider>
      </body>
    </html>
  );
}
